import React from 'react';
import { X, Printer, Download, Bot, CheckCircle2, AlertTriangle, ShieldCheck } from 'lucide-react';

export default function ReportModal({ isOpen, onClose, agentData, product, quantity, targetDate }) {
  if (!isOpen) return null;

  const handlePrint = () => {
    window.print();
  };

  const currentDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  return (
    <div className="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-4 sm:p-6 overflow-y-auto">
      <div className="bg-white rounded-2xl shadow-2xl max-w-4xl w-full max-h-[90vh] flex flex-col overflow-hidden border border-slate-200">
        
        {/* Modal Header */}
        <div className="p-4 sm:p-5 border-b border-slate-100 flex items-center justify-between no-print bg-slate-50/70">
          <div className="flex items-center gap-2">
            <span className="w-3 h-3 rounded-full bg-emerald-500"></span>
            <h3 className="font-bold text-slate-900 text-base">Executive Procurement Report</h3>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              className="inline-flex items-center px-3.5 py-1.5 rounded-lg text-xs font-bold text-white bg-indigo-600 hover:bg-indigo-700 shadow-xs transition-all"
            >
              <Printer className="w-3.5 h-3.5 mr-1.5" />
              Print / Save as PDF
            </button>
            <button
              onClick={onClose}
              className="p-1.5 rounded-lg text-slate-400 hover:text-slate-600 hover:bg-slate-200/60 transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Printable Document Area */}
        <div id="printable-report" className="p-6 sm:p-8 overflow-y-auto space-y-6 text-slate-800 font-sans">
          
          {/* Document Header */}
          <div className="flex flex-col sm:flex-row justify-between sm:items-start border-b border-slate-200 pb-6 gap-4">
            <div>
              <div className="flex items-center gap-2 mb-1">
                <div className="w-7 h-7 rounded-lg bg-indigo-600 flex items-center justify-center text-white font-black text-sm">
                  AI
                </div>
                <h1 className="text-xl font-black tracking-tight text-slate-900">
                  Automated Raw Material Requirement & Procurement Report
                </h1>
              </div>
              <p className="text-xs text-slate-500">
                Generated by Autonomous Manufacturing Supply Chain Planning Agent
              </p>
            </div>

            <div className="text-right text-xs text-slate-500 font-mono space-y-1">
              <p>Report Date: <strong className="text-slate-800">{currentDate}</strong></p>
              <p>Status: <strong className="text-emerald-700">VERIFIED BY AGENT</strong></p>
              <p>Ref: <strong className="text-slate-800">MR-PLAN-{Date.now().toString().slice(-6)}</strong></p>
            </div>
          </div>

          {/* Production Order Metadata */}
          <div className="bg-slate-50 p-4 rounded-xl border border-slate-200 grid grid-cols-2 sm:grid-cols-4 gap-4 text-xs">
            <div>
              <span className="text-slate-400 uppercase font-bold text-[10px] block">Target Product</span>
              <strong className="text-slate-900 text-sm font-bold">{product?.name || 'Office Chair'}</strong>
            </div>
            <div>
              <span className="text-slate-400 uppercase font-bold text-[10px] block">Production Quantity</span>
              <strong className="text-slate-900 text-sm font-bold">{quantity} units</strong>
            </div>
            <div>
              <span className="text-slate-400 uppercase font-bold text-[10px] block">Target Production Date</span>
              <strong className="text-slate-900 text-sm font-bold">{targetDate || 'Immediate'}</strong>
            </div>
            <div>
              <span className="text-slate-400 uppercase font-bold text-[10px] block">Safety Stock Policy</span>
              <strong className="text-indigo-700 text-sm font-bold">100% Buffer Enforced</strong>
            </div>
          </div>

          {/* Table: Materials, Stock, Shortages, Procurement */}
          <div>
            <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">
              Comprehensive Bill of Materials & Procurement Matrix
            </h3>
            <div className="border border-slate-200 rounded-xl overflow-hidden">
              <table className="w-full text-left border-collapse text-xs">
                <thead>
                  <tr className="bg-slate-100/80 border-b border-slate-200 font-bold text-slate-700">
                    <th className="py-2.5 px-3">Material</th>
                    <th className="py-2.5 px-3">Unit</th>
                    <th className="py-2.5 px-3 text-right">Gross Required</th>
                    <th className="py-2.5 px-3 text-right">Current Stock</th>
                    <th className="py-2.5 px-3 text-right">Safety Stock</th>
                    <th className="py-2.5 px-3 text-right">Available Usable</th>
                    <th className="py-2.5 px-3 text-right">Shortage</th>
                    <th className="py-2.5 px-3 text-right font-black text-rose-700">Recommended Purchase</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {agentData && agentData.materials ? (
                    agentData.materials.map((m) => (
                      <tr key={m.materialId || m.name}>
                        <td className="py-2.5 px-3 font-semibold text-slate-900">{m.name}</td>
                        <td className="py-2.5 px-3 text-slate-500 font-mono">{m.unit}</td>
                        <td className="py-2.5 px-3 text-right font-medium">{m.totalRequired.toLocaleString()}</td>
                        <td className="py-2.5 px-3 text-right">{m.currentStock.toLocaleString()}</td>
                        <td className="py-2.5 px-3 text-right text-slate-500">{m.safetyStock.toLocaleString()}</td>
                        <td className="py-2.5 px-3 text-right font-semibold text-slate-800">{m.availableUsableStock.toLocaleString()}</td>
                        <td className="py-2.5 px-3 text-right">
                          <span className={m.shortage > 0 ? 'text-rose-600 font-bold' : 'text-slate-400'}>
                            {m.shortage > 0 ? m.shortage.toLocaleString() : '0'}
                          </span>
                        </td>
                        <td className="py-2.5 px-3 text-right font-bold">
                          {m.purchaseRequirement > 0 ? (
                            <span className="text-rose-700 font-black">+{m.purchaseRequirement.toLocaleString()} {m.unit}</span>
                          ) : (
                            <span className="text-emerald-700">0 (Sufficient)</span>
                          )}
                        </td>
                      </tr>
                    ))
                  ) : null}
                </tbody>
              </table>
            </div>
          </div>

          {/* AI Synthesis Box */}
          <div className="border border-indigo-100 bg-indigo-50/40 p-4 rounded-xl text-xs space-y-2">
            <div className="flex items-center gap-1.5 font-bold text-indigo-900">
              <Bot className="w-4 h-4 text-indigo-600" />
              <span>AI Agent Planning Synthesis</span>
            </div>
            <p className="text-slate-700 whitespace-pre-line leading-relaxed font-sans">
              {agentData?.summary}
            </p>
          </div>

          {/* Signoff / Viva Note */}
          <div className="pt-4 border-t border-slate-200 flex justify-between items-end text-[11px] text-slate-400">
            <div>
              <p>Formulae Enforced:</p>
              <p className="font-mono">Available Usable = Current - Safety | Purchase = max(0, Required - Usable)</p>
            </div>
            <div className="text-right">
              <p className="font-semibold text-slate-700">Automated Agentic AI Verification</p>
              <p>College Demo / Viva Presentation</p>
            </div>
          </div>

        </div>

      </div>
    </div>
  );
}
